"""create tables

Revision ID: a49a94b3fc47
Revises: 
Create Date: 2025-01-11 13:19:18.054389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a49a94b3fc47"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cat",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("years_of_experience", sa.Integer(), nullable=False),
        sa.Column("breed", sa.String(), nullable=False),
        sa.Column("salary", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cat")),
    )
    op.create_index(op.f("ix_cat_id"), "cat", ["id"], unique=False)
    op.create_table(
        "mission",
        sa.Column("cat_id", sa.Integer(), nullable=True),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cat_id"],
            ["cat.id"],
            name=op.f("fk_mission_cat_id_cat"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission")),
    )
    op.create_index(op.f("ix_mission_id"), "mission", ["id"], unique=False)
    op.create_table(
        "target",
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["mission.id"],
            name=op.f("fk_target_mission_id_mission"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target")),
    )
    op.create_index(op.f("ix_target_id"), "target", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_target_id"), table_name="target")
    op.drop_table("target")
    op.drop_index(op.f("ix_mission_id"), table_name="mission")
    op.drop_table("mission")
    op.drop_index(op.f("ix_cat_id"), table_name="cat")
    op.drop_table("cat")
    # ### end Alembic commands ###
